repos:
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.19.1
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: [".[jinjafmt]"]
        files: "^(models|macros)/.*"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        exclude: "^(dbt_packages|target|webapp)/.*"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
      - id: ruff-format
