name: "github"
version: "1.0.0"
config-version: 2

profile: "github"

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  github:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
    consumers:
      +materialized: table
      +schema: consumers
      xebia:
        +schema: consumers_xebia

vars:
  author_string: "{% for author in var('authors') %}{{author.name}},{% endfor %}"
  authors:
    - name: JCZuurmond
      organization: Xebia
    - name: jwills
      organization: NA
    - name: ManousogiannisM
      organization: Xebia
    - name: timotk
      organization: Xebia
    - name: ramonvermeulen
      organization: Xebia
    - name: RicardoAGL
      organization: Xebia
    - name: pgoslatara
      organization: Xebia
    - name: Fokko
      organization: Tabular
    - name: NielsZeilemaker
      organization: Xebia
    - name: jochemloedeman
      organization: Xebia
    - name: yildizali
      organization: Xebia
    - name: Roymprog
      organization: Xebia
    - name: gglanzani
      organization: Xebia
    - name: jessehouwing
      organization: Xebia
    - name: @0xR
      organization: Xebia
    - name: @AlbertBrand
      organization: Xebia
    - name: @alycklama
      organization: Xebia
    - name: @bschaatsbergen
      organization: Xebia
    - name: @chtzvt
      organization: Xebia
    - name: @cloudcosmonaut
      organization: Xebia
    - name: @cvs79
      organization: Xebia
    - name: @DanielRieske
      organization: Xebia
    - name: @dgniewek
      organization: Xebia
    - name: @droosma
      organization: Xebia
    - name: @fvanwijk
      organization: Xebia
    - name: @hernanif1
      organization: Xebia
    - name: @hierynomus
      organization: Xebia
    - name: @Jacco
      organization: Xebia
    - name: @jwbargsten
      organization: Xebia
    - name: @krisgeus
      organization: Xebia
    - name: @laurensknoll
      organization: Xebia
    - name: @NoirNoble
      organization: Xebia
    - name: @Nr18
      organization: Xebia
    - name: @OmnipotentOwl
      organization: Xebia
    - name: @ramonvermeulen
      organization: Xebia
    - name: @sanderaernouts
      organization: Xebia
    - name: @sujithq
      organization: Xebia
    - name: @ThijSlim
      organization: Xebia
    - name: @thomas
      organization: Xebia
    - name: @tiborhercz
      organization: Xebia
    - name: @Yeseh
      organization: Xebia
    - name: @mwiewior
      organization: Xebia
