name: "github"
version: "1.0.0"
config-version: 2

profile: "github"

model-paths: ["models"]

clean-targets:
- "target"
- "dbt_packages"

models:
  github:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
    consumers:
      +materialized: table
      +schema: consumers

vars:
  authors:
  - JCZuurmond
  - jwills
  - ManousogiannisM
