name: "github"
version: "1.0.0"
config-version: 2

profile: "github"

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  github:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
    consumers:
      +materialized: table
      +schema: consumers
      xebia:
        +schema: consumers_xebia

vars:
  author_string: "{% for author in var('authors') %}{{author.name}},{% endfor %}"
  authors:
    - name: JCZuurmond
      organization: Xebia
    - name: jwills
      organization: NA
    - name: ManousogiannisM
      organization: Xebia
    - name: timotk
      organization: Xebia
    - name: ramonvermeulen
      organization: Xebia
    - name: RicardoAGL
      organization: Xebia
    - name: pgoslatara
      organization: Xebia
    - name: Fokko
      organization: Tabular
    - name: NielsZeilemaker
      organization: Xebia
    - name: jochemloedeman
      organization: Xebia
    - name: yildizali
      organization: Xebia
    - name: Roymprog
      organization: Xebia
    - name: gglanzani
      organization: Xebia
    - name: jessehouwing
      organization: Xebia
    - name: kzarzycki
      organization: Xebia
    - name: mobuchowski
      organization: Xebia
    - name: mwiewior
      organization: Xebia
    - name: JDarDagran
      organization: Xebia
    - name: maciejmacq-dev
      organization: Xebia
    - name: andrzejdackiewicz
      organization: Xebia
    - name: pawel-big-lebowski
      organization: Xebia
    - name: dgniewek
      organization: Xebia
    - name: santhin
      organization: Xebia
    - name: Lasica
      organization: Xebia
    - name: jakubigla
      organization: Xebia
    - name: jacops
      organization: Xebia
    - name: kacpermuda
      organization: Xebia
    - name: calychas
      organization: Xebia
    - name: p-pekala
      organization: Xebia
    - name: michalrudko
      organization: Xebia
    - name: michalbrys
      organization: Xebia
    - name: marrrcin
      organization: Xebia
