github:
  target: default
  outputs:
    default:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      settings:
        pandas_analyze_sample: 100000
      plugins:
        - module: github_contributions.plugin
          alias: github_contributions
          config:
            debug: true
            cache: true
