SELECT
    CAST(id AS BIGINT) AS id,
    CAST(node_id AS VARCHAR) AS node_id,
    CAST(name AS VARCHAR) AS name,
    CAST(full_name AS VARCHAR) AS full_name,
    CAST(private AS BOOLEAN) AS private,

    -- owner
    CAST(owner.login AS VARCHAR) AS owner_login,
    CAST(owner.id AS INTEGER) AS owner_id,
    CAST(owner.node_id AS VARCHAR) AS owner_node_id,
    CAST(owner.avatar_url AS VARCHAR) AS owner_avatar_url,
    CAST(owner.gravatar_id AS VARCHAR) AS owner_gravatar_id,
    CAST(owner.url AS VARCHAR) AS owner_url,
    CAST(owner.html_url AS VARCHAR) AS owner_html_url,
    CAST(owner.followers_url AS VARCHAR) AS owner_followers_url,
    CAST(owner.following_url AS VARCHAR) AS owner_following_url,
    CAST(owner.gists_url AS VARCHAR) AS owner_gists_url,
    CAST(owner.starred_url AS VARCHAR) AS owner_starred_url,
    CAST(owner.subscriptions_url AS VARCHAR) AS owner_subscriptions_url,
    CAST(owner.organizations_url AS VARCHAR) AS owner_organizations_url,
    CAST(owner.repos_url AS VARCHAR) AS owner_repos_url,
    CAST(owner.events_url AS VARCHAR) AS owner_events_url,
    CAST(owner.received_events_url AS VARCHAR) AS owner_received_events_url,
    CAST(owner."type" AS VARCHAR) AS owner_type,
    CAST(owner.site_admin AS BOOLEAN) AS owner_site_admin,

    CAST(html_url AS VARCHAR) AS html_url,
    CAST(description AS VARCHAR) AS description,
    CAST(fork AS BOOLEAN) AS fork,
    CAST(url AS VARCHAR) AS url,
    CAST(forks_url AS VARCHAR) AS forks_url,
    CAST(keys_url AS VARCHAR) AS keys_url,
    CAST(collaborators_url AS VARCHAR) AS collaborators_url,
    CAST(teams_url AS VARCHAR) AS teams_url,
    CAST(hooks_url AS VARCHAR) AS hooks_url,
    CAST(issue_events_url AS VARCHAR) AS issue_events_url,
    CAST(events_url AS VARCHAR) AS events_url,
    CAST(assignees_url AS VARCHAR) AS assignees_url,
    CAST(branches_url AS VARCHAR) AS branches_url,
    CAST(tags_url AS VARCHAR) AS tags_url,
    CAST(blobs_url AS VARCHAR) AS blobs_url,
    CAST(git_tags_url AS VARCHAR) AS git_tags_url,
    CAST(git_refs_url AS VARCHAR) AS git_refs_url,
    CAST(trees_url AS VARCHAR) AS trees_url,
    CAST(statuses_url AS VARCHAR) AS statuses_url,
    CAST(languages_url AS VARCHAR) AS languages_url,
    CAST(stargazers_url AS VARCHAR) AS stargazers_url,
    CAST(contributors_url AS VARCHAR) AS contributors_url,
    CAST(subscribers_url AS VARCHAR) AS subscribers_url,
    CAST(subscription_url AS VARCHAR) AS subscription_url,
    CAST(commits_url AS VARCHAR) AS commits_url,
    CAST(git_commits_url AS VARCHAR) AS git_commits_url,
    CAST(comments_url AS VARCHAR) AS comments_url,
    CAST(issue_comment_url AS VARCHAR) AS issue_comment_url,
    CAST(contents_url AS VARCHAR) AS contents_url,
    CAST(compare_url AS VARCHAR) AS compare_url,
    CAST(merges_url AS VARCHAR) AS merges_url,
    CAST(archive_url AS VARCHAR) AS archive_url,
    CAST(downloads_url AS VARCHAR) AS downloads_url,
    CAST(issues_url AS VARCHAR) AS issues_url,
    CAST(pulls_url AS VARCHAR) AS pulls_url,
    CAST(milestones_url AS VARCHAR) AS milestones_url,
    CAST(notifications_url AS VARCHAR) AS notifications_url,
    CAST(labels_url AS VARCHAR) AS labels_url,
    CAST(releases_url AS VARCHAR) AS releases_url,
    CAST(deployments_url AS VARCHAR) AS deployments_url,
    CAST(created_at AS VARCHAR) AS created_at,
    CAST(updated_at AS VARCHAR) AS updated_at,
    CAST(pushed_at AS VARCHAR) AS pushed_at,
    CAST(git_url AS VARCHAR) AS git_url,
    CAST(ssh_url AS VARCHAR) AS ssh_url,
    CAST(clone_url AS VARCHAR) AS clone_url,
    CAST(svn_url AS VARCHAR) AS svn_url,
    CAST(homepage AS VARCHAR) AS homepage,
    CAST(size AS BIGINT) AS size,
    CAST(stargazers_count AS BIGINT) AS stargazers_count,
    CAST(watchers_count AS BIGINT) AS watchers_count,
    CAST(language AS VARCHAR) AS language,
    CAST(has_issues AS BOOLEAN) AS has_issues,
    CAST(has_projects AS BOOLEAN) AS has_projects,
    CAST(has_downloads AS BOOLEAN) AS has_downloads,
    CAST(has_wiki AS BOOLEAN) AS has_wiki,
    CAST(has_pages AS BOOLEAN) AS has_pages,
    CAST(has_discussions AS BOOLEAN) AS has_discussions,
    CAST(forks_count AS BIGINT) AS forks_count,
    CAST(mirror_url AS INTEGER) AS mirror_url,
    CAST(archived AS BOOLEAN) AS archived,
    CAST(disabled AS BOOLEAN) AS disabled,
    CAST(open_issues_count AS BIGINT) AS open_issues_count,

    -- license
    CAST(license."key" AS VARCHAR) AS license_key,
    CAST(license."name" AS VARCHAR) AS license_name,
    CAST(license.spdx_id AS VARCHAR) AS license_spdx_id,
    CAST(license.url AS VARCHAR) AS license_url,
    CAST(license.node_id AS VARCHAR) AS license_node_id,

    CAST(allow_forking AS BOOLEAN) AS allow_forking,
    CAST(is_template AS BOOLEAN) AS is_template,
    CAST(web_commit_signoff_required AS BOOLEAN) AS web_commit_signoff_required,

    -- labels : Can not select because is a list
    -- CAST(topics AS INTEGER) AS topics,

    CAST(visibility AS VARCHAR) AS visibility,
    CAST(forks AS BIGINT) AS forks,
    CAST(open_issues AS BIGINT) AS open_issues,
    CAST(watchers AS BIGINT) AS watchers,
    CAST(default_branch AS VARCHAR) AS default_branch,
    CAST(temp_clone_token AS INTEGER) AS temp_clone_token,

    -- organization
    -- CAST(organization.login AS VARCHAR) AS organization_login,
    -- CAST(organization.id AS INTEGER) AS organization_id,
    -- CAST(organization.node_id AS VARCHAR) AS organization_node_id,
    -- CAST(organization.avatar_url AS VARCHAR) AS organization_avatar_url,
    -- CAST(organization.gravatar_id AS VARCHAR) AS organization_gravatar_id,
    -- CAST(organization.url AS VARCHAR) AS organization_url,
    -- CAST(organization.html_url AS VARCHAR) AS organization_html_url,
    -- CAST(organization.followers_url AS VARCHAR) AS organization_followers_url,
    -- CAST(organization.following_url AS VARCHAR) AS organization_following_url,
    -- CAST(organization.gists_url AS VARCHAR) AS organization_gists_url,
    -- CAST(organization.starred_url AS VARCHAR) AS organization_starred_url,
    -- CAST(organization.subscriptions_url AS VARCHAR) AS organization_subscriptions_url,
    -- CAST(organization.organizations_url AS VARCHAR) AS organization_organizations_url,
    -- CAST(organization.repos_url AS VARCHAR) AS organization_repos_url,
    -- CAST(organization.events_url AS VARCHAR) AS organization_events_url,
    -- CAST(organization.received_events_url AS VARCHAR) AS organization_received_events_url,
    -- CAST(organization."type" AS VARCHAR) AS organization_type,
    -- CAST(organization.site_admin AS BOOLEAN) AS organization_site_admin,

    CAST(network_count AS BIGINT) AS network_count,
    CAST(subscribers_count AS BIGINT) AS subscribers_count,
FROM {{ source('github_contributions', 'src_repositories') }}
