select
    cast(url as varchar) as url,
    cast(repository_url as varchar) as repository_url,
    cast(labels_url as varchar) as labels_url,
    cast(comments_url as varchar) as comments_url,
    cast(events_url as varchar) as events_url,
    cast(html_url as varchar) as html_url,
    cast(id as bigint) as id,
    cast(node_id as varchar) as node_id,
    cast("number" as bigint) as "number",
    cast(title as varchar) as title,

    -- user
    cast(user.login as varchar) as user_login,
    cast(user.id as integer) as user_id,
    cast(user.node_id as varchar) as user_node_id,
    cast(user.avatar_url as varchar) as user_avatar_url,
    cast(user.gravatar_id as varchar) as user_gravatar_id,
    cast(user.url as varchar) as user_url,
    cast(user.html_url as varchar) as user_html_url,
    cast(user.followers_url as varchar) as user_followers_url,
    cast(user.following_url as varchar) as user_following_url,
    cast(user.gists_url as varchar) as user_gists_url,
    cast(user.starred_url as varchar) as user_starred_url,
    cast(user.subscriptions_url as varchar) as user_subscription_url,
    cast(user.organizations_url as varchar) as user_organizations_url,
    cast(user.repos_url as varchar) as user_repose_url,
    cast(user.events_url as varchar) as user_events_url,
    cast(user.received_events_url as varchar) as user_received_events_url,
    cast(user."type" as varchar) as user_type,
    cast(user.site_admin as boolean) as user_site_admin,

    -- labels : Can not select because is a list
    -- CAST(labels.id AS BIGINT) As labels_id,
    -- CAST(labels.node_id AS VARCHAR) AS labels_node_id,
    -- CAST(labels.url AS VARCHAR) AS labels_url,
    -- CAST(labels.name AS VARCHAR) AS labels_name,
    -- CAST(labels.color AS VARCHAR) AS labels_color,
    -- CAST(labels.default AS BOOLEAN) AS labels_default,
    -- CAST(labels.description AS VARCHAR) AS labels_description,
    cast(state as varchar) as state,
    cast(locked as boolean) as locked,

    -- assignee
    cast(assignee.login as varchar) as assignee_login,
    cast(assignee.id as integer) as assignee_id,
    cast(assignee.node_id as varchar) as assignee_node_id,
    cast(assignee.avatar_url as varchar) as assignee_avatar_url,
    cast(assignee.gravatar_id as varchar) as assignee_gravatar_id,
    cast(assignee.url as varchar) as assignee_url,
    cast(assignee.html_url as varchar) as assignee_html_url,
    cast(assignee.followers_url as varchar) as assignee_followers_url,
    cast(assignee.following_url as varchar) as assignee_following_url,
    cast(assignee.gists_url as varchar) as assignee_gists_url,
    cast(assignee.starred_url as varchar) as assignee_starred_url,
    cast(assignee.subscriptions_url as varchar) as assignee_subscriptions_url,
    cast(assignee.organizations_url as varchar) as assignee_organizations_url,
    cast(assignee.repos_url as varchar) as assignee_repos_url,
    cast(assignee.events_url as varchar) as assignee_events_url,
    cast(assignee.received_events_url as varchar) as assignee_received_events_url,
    cast(assignee."type" as varchar) as assignee_type,
    cast(assignee.site_admin as boolean) as assignee_site_admin,

    -- assignees - Can not select because is a list
    -- CAST(assignees.login AS VARCHAR) AS assignees_login,
    -- CAST(assignees.id AS INTEGER) AS assignees_id,
    -- CAST(assignees.node_id AS VARCHAR) AS assignees_node_id,
    -- CAST(assignees.avatar_url AS VARCHAR) AS assignees_avatar_url,
    -- CAST(assignees.gravatar_id AS VARCHAR) AS assignees_gravatar_id,
    -- CAST(assignees.url AS VARCHAR) AS assignees_url,
    -- CAST(assignees.html_url AS VARCHAR) AS assignees_html_url,
    -- CAST(assignees.followers_url AS VARCHAR) AS assignees_followers_url,
    -- CAST(assignees.following_url AS VARCHAR) AS assignees_following_url,
    -- CAST(assignees.gists_url AS VARCHAR) AS assignees_gists_url,
    -- CAST(assignees.starred_url AS VARCHAR) AS assignees_starred_url,
    -- CAST(assignees.subscriptions_url AS VARCHAR) AS assignees_subscriptions_url,
    -- CAST(assignees.organizations_url AS VARCHAR) AS assignees_organizations_url,
    -- CAST(assignees.repos_url AS VARCHAR) AS assignees_repos_url,
    -- CAST(assignees.events_url AS VARCHAR) AS assignees_events_url,
    -- CAST(assignees.received_events_url AS VARCHAR) AS assignees_received_events_url,
    -- CAST(assignees."type" AS VARCHAR) AS assignees_type,
    -- CAST(assignees.site_admin AS BOOLEAN) AS assignees_site_admin,
    -- milestone
    cast(milestone.url as varchar) as milestone_url,
    cast(milestone.html_url as varchar) as milestone_html_url,
    cast(milestone.labels_url as varchar) as milestone_labels_url,
    cast(milestone.id as integer) as milestone_id,
    cast(milestone.node_id as varchar) as milestone_node_id,
    cast(milestone.number as tinyint) as milestone_number,
    cast(milestone.title as varchar) as milestone_title,
    cast(milestone.description as varchar) as milestone_description,
    cast(milestone.open_issues as tinyint) as milestone_open_issues,
    cast(milestone.closed_issues as tinyint) as milestone_closed_issues,
    cast(milestone.state as varchar) as milestone_state,
    cast(milestone.created_at as varchar) as milestone_created_at,
    cast(milestone.updated_at as varchar) as milestone_updated_at,
    cast(milestone.due_on as varchar) as milestone_due_on,
    cast(milestone.closed_at as varchar) as milestone_closed_at,

    -- milestone.creator
    cast(milestone.creator.login as varchar) as milestone_creator_login,
    cast(milestone.creator.id as integer) as milestone_creator_id,
    cast(milestone.creator.node_id as varchar) as milestone_creator_node_id,
    cast(milestone.creator.avatar_url as varchar) as milestone_creator_avatar_url,
    cast(milestone.creator.gravatar_id as varchar) as milestone_creator_gravatar_id,
    cast(milestone.creator.url as varchar) as milestone_creator_url,
    cast(milestone.creator.html_url as varchar) as milestone_creator_html_url,
    cast(milestone.creator.followers_url as varchar) as milestone_creator_followers_url,
    cast(milestone.creator.following_url as varchar) as milestone_creator_following_url,
    cast(milestone.creator.gists_url as varchar) as milestone_creator_gists_url,
    cast(milestone.creator.starred_url as varchar) as milestone_creator_starred_url,
    cast(
        milestone.creator.subscriptions_url as varchar
    ) as milestone_creator_subscriptions_url,
    cast(
        milestone.creator.organizations_url as varchar
    ) as milestone_creator_organizations_url,
    cast(milestone.creator.repos_url as varchar) as milestone_creator_repos_url,
    cast(milestone.creator.events_url as varchar) as milestone_creator_events_url,
    cast(
        milestone.creator.received_events_url as varchar
    ) as milestone_creator_received_events_url,
    cast(milestone.creator."type" as varchar) as milestone_creator_type,
    cast(milestone.creator.site_admin as boolean) as site_admin,

    cast(comments as bigint) as comments,
    cast(created_at as varchar) as created_at,
    cast(updated_at as varchar) as updated_at,
    cast(closed_at as varchar) as closed_at,
    cast(author_association as varchar) as author_association,
    cast(active_lock_reason as varchar) as active_lock_reason,
    cast(draft as boolean) as draft,

    -- pull_request
    cast(pull_request.url as varchar) as pull_request_url,
    cast(pull_request.html_url as varchar) as pull_request_html_url,
    cast(pull_request.diff_url as varchar) as pull_request_diff_url,
    cast(pull_request.patch_url as varchar) as pull_request_patch_url,
    cast(pull_request.merged_at as varchar) as pull_request_merged_at,

    cast(body as varchar) as body,

    -- reactions
    cast(reactions.url as varchar) as reactions_url,
    cast(reactions.total_count as tinyint) as reactions_total_count,
    cast(reactions."+1" as tinyint) as reactions_plus_one,
    cast(reactions."-1" as tinyint) as reactions_minus_one,
    cast(reactions.laugh as tinyint) as reactions_laugh,
    cast(reactions.hooray as tinyint) as reactions_hooray,
    cast(reactions.confused as tinyint) as reactions_confused,
    cast(reactions.heart as tinyint) as reactions_heart,
    cast(reactions.rocket as tinyint) reactions_rocket,
    cast(reactions.eyes as tinyint) as reactions_eyes,

    cast(timeline_url as varchar) as timeline_url,
    cast(performed_via_github_app as integer) as performed_via_github_app,
    cast(state_reason as integer) as state_reason,
    cast(score as double) as score,

from {{ source("github_contributions", "src_pull_requests") }}
