select
    cast(id as bigint) as id,
    cast(node_id as varchar) as node_id,
    cast(name as varchar) as name,
    cast(full_name as varchar) as full_name,
    cast(private as boolean) as private,

    -- owner
    cast(owner.login as varchar) as owner_login,
    cast(owner.id as integer) as owner_id,
    cast(owner.node_id as varchar) as owner_node_id,
    cast(owner.avatar_url as varchar) as owner_avatar_url,
    cast(owner.gravatar_id as varchar) as owner_gravatar_id,
    cast(owner.url as varchar) as owner_url,
    cast(owner.html_url as varchar) as owner_html_url,
    cast(owner.followers_url as varchar) as owner_followers_url,
    cast(owner.following_url as varchar) as owner_following_url,
    cast(owner.gists_url as varchar) as owner_gists_url,
    cast(owner.starred_url as varchar) as owner_starred_url,
    cast(owner.subscriptions_url as varchar) as owner_subscriptions_url,
    cast(owner.organizations_url as varchar) as owner_organizations_url,
    cast(owner.repos_url as varchar) as owner_repos_url,
    cast(owner.events_url as varchar) as owner_events_url,
    cast(owner.received_events_url as varchar) as owner_received_events_url,
    cast(owner."type" as varchar) as owner_type,
    cast(owner.site_admin as boolean) as owner_site_admin,

    cast(html_url as varchar) as html_url,
    cast(description as varchar) as description,
    cast(fork as boolean) as fork,
    cast(url as varchar) as url,
    cast(forks_url as varchar) as forks_url,
    cast(keys_url as varchar) as keys_url,
    cast(collaborators_url as varchar) as collaborators_url,
    cast(teams_url as varchar) as teams_url,
    cast(hooks_url as varchar) as hooks_url,
    cast(issue_events_url as varchar) as issue_events_url,
    cast(events_url as varchar) as events_url,
    cast(assignees_url as varchar) as assignees_url,
    cast(branches_url as varchar) as branches_url,
    cast(tags_url as varchar) as tags_url,
    cast(blobs_url as varchar) as blobs_url,
    cast(git_tags_url as varchar) as git_tags_url,
    cast(git_refs_url as varchar) as git_refs_url,
    cast(trees_url as varchar) as trees_url,
    cast(statuses_url as varchar) as statuses_url,
    cast(languages_url as varchar) as languages_url,
    cast(stargazers_url as varchar) as stargazers_url,
    cast(contributors_url as varchar) as contributors_url,
    cast(subscribers_url as varchar) as subscribers_url,
    cast(subscription_url as varchar) as subscription_url,
    cast(commits_url as varchar) as commits_url,
    cast(git_commits_url as varchar) as git_commits_url,
    cast(comments_url as varchar) as comments_url,
    cast(issue_comment_url as varchar) as issue_comment_url,
    cast(contents_url as varchar) as contents_url,
    cast(compare_url as varchar) as compare_url,
    cast(merges_url as varchar) as merges_url,
    cast(archive_url as varchar) as archive_url,
    cast(downloads_url as varchar) as downloads_url,
    cast(issues_url as varchar) as issues_url,
    cast(pulls_url as varchar) as pulls_url,
    cast(milestones_url as varchar) as milestones_url,
    cast(notifications_url as varchar) as notifications_url,
    cast(labels_url as varchar) as labels_url,
    cast(releases_url as varchar) as releases_url,
    cast(deployments_url as varchar) as deployments_url,
    cast(created_at as varchar) as created_at,
    cast(updated_at as varchar) as updated_at,
    cast(pushed_at as varchar) as pushed_at,
    cast(git_url as varchar) as git_url,
    cast(ssh_url as varchar) as ssh_url,
    cast(clone_url as varchar) as clone_url,
    cast(svn_url as varchar) as svn_url,
    cast(homepage as varchar) as homepage,
    cast(size as bigint) as size,
    cast(stargazers_count as bigint) as stargazers_count,
    cast(watchers_count as bigint) as watchers_count,
    cast(language as varchar) as language,
    cast(has_issues as boolean) as has_issues,
    cast(has_projects as boolean) as has_projects,
    cast(has_downloads as boolean) as has_downloads,
    cast(has_wiki as boolean) as has_wiki,
    cast(has_pages as boolean) as has_pages,
    cast(has_discussions as boolean) as has_discussions,
    cast(forks_count as bigint) as forks_count,
    cast(mirror_url as integer) as mirror_url,
    cast(archived as boolean) as archived,
    cast(disabled as boolean) as disabled,
    cast(open_issues_count as bigint) as open_issues_count,

    -- license
    cast(license."key" as varchar) as license_key,
    cast(license."name" as varchar) as license_name,
    cast(license.spdx_id as varchar) as license_spdx_id,
    cast(license.url as varchar) as license_url,
    cast(license.node_id as varchar) as license_node_id,

    cast(allow_forking as boolean) as allow_forking,
    cast(is_template as boolean) as is_template,
    cast(web_commit_signoff_required as boolean) as web_commit_signoff_required,

    -- labels : Can not select because is a list
    -- CAST(topics AS INTEGER) AS topics,
    cast(visibility as varchar) as visibility,
    cast(forks as bigint) as forks,
    cast(open_issues as bigint) as open_issues,
    cast(watchers as bigint) as watchers,
    cast(default_branch as varchar) as default_branch,
    cast(temp_clone_token as integer) as temp_clone_token,

    -- organization
    -- CAST(organization.login AS VARCHAR) AS organization_login,
    -- CAST(organization.id AS INTEGER) AS organization_id,
    -- CAST(organization.node_id AS VARCHAR) AS organization_node_id,
    -- CAST(organization.avatar_url AS VARCHAR) AS organization_avatar_url,
    -- CAST(organization.gravatar_id AS VARCHAR) AS organization_gravatar_id,
    -- CAST(organization.url AS VARCHAR) AS organization_url,
    -- CAST(organization.html_url AS VARCHAR) AS organization_html_url,
    -- CAST(organization.followers_url AS VARCHAR) AS organization_followers_url,
    -- CAST(organization.following_url AS VARCHAR) AS organization_following_url,
    -- CAST(organization.gists_url AS VARCHAR) AS organization_gists_url,
    -- CAST(organization.starred_url AS VARCHAR) AS organization_starred_url,
    -- CAST(organization.subscriptions_url AS VARCHAR) AS
    -- organization_subscriptions_url,
    -- CAST(organization.organizations_url AS VARCHAR) AS
    -- organization_organizations_url,
    -- CAST(organization.repos_url AS VARCHAR) AS organization_repos_url,
    -- CAST(organization.events_url AS VARCHAR) AS organization_events_url,
    -- CAST(organization.received_events_url AS VARCHAR) AS
    -- organization_received_events_url,
    -- CAST(organization."type" AS VARCHAR) AS organization_type,
    -- CAST(organization.site_admin AS BOOLEAN) AS organization_site_admin,
    cast(network_count as bigint) as network_count,
    cast(subscribers_count as bigint) as subscribers_count,
from {{ source("github_contributions", "src_repositories") }}
