select
    title,
    body,
    user_login as author,
    author_association,
    owner_and_repository.full_repository_name,
    owner_and_repository.owner,
    owner_and_repository.repository,
    state,
    draft,
    comments,
    created_at,
    updated_at,
    closed_at,
    pull_request_merged_at as merged_at,
    reactions_total_count,
    html_url as url,
from {{ ref("int_pull_requests") }}
