name: Pull request checks

on:
  pull_request:
    paths:
      - "models/**"
      - "github_contributions/**"
env:
  DUCKDB_PATH: github_contributions.duckdb

jobs:
  soda_scan:
    runs-on: ubuntu-latest
    name: Run Soda Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download duckdb
        uses: dawidd6/action-download-artifact@v2
        with:
          name: ${{ env.DUCKDB_PATH }}
          workflow: dbt.yml
          workflow_conclusion: success

      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@v1.0.2
        env:
          SODA_CLOUD_API_KEY: ${{ secrets.SODA_CLOUD_API_KEY }}
          SODA_CLOUD_API_SECRET: ${{ secrets.SODA_CLOUD_API_SECRET }}
          DUCKDB_PATH: /tmp/workspace/${{ env.DUCKDB_PATH }}
          SCHEMA: main
        with:
          soda_library_version: v1.1.12
          data_source: github_contributions
          configuration: ./soda_configuration.yml
          checks: ./soda_checks.yml
